import { Activity, Component, createElement, Fragment, Profiler, StrictMode, Suspense } from 'react'

export { Activity, Component, createElement, Fragment, Profiler, StrictMode, Suspense }

// Behavior
export const area = createElement.bind(null, 'area')
export const br = createElement.bind(null, 'br')
export const button = createElement.bind(null, 'button')
export const canvas = createElement.bind(null, 'canvas')
export const details = createElement.bind(null, 'details')
export const dialog = createElement.bind(null, 'dialog')
export const hr = createElement.bind(null, 'hr')
export const map = createElement.bind(null, 'map')
export const meter = createElement.bind(null, 'meter')
export const noscript = createElement.bind(null, 'noscript')
export const progress = createElement.bind(null, 'progress')
export const slot = createElement.bind(null, 'slot')
export const style = createElement.bind(null, 'style')
export const template = createElement.bind(null, 'template')

// Text
export const b = createElement.bind(null, 'b')
export const bdi = createElement.bind(null, 'bdi')
export const bdo = createElement.bind(null, 'bdo')
export const blockquote = createElement.bind(null, 'blockquote')
export const del = createElement.bind(null, 'del')
export const em = createElement.bind(null, 'em')
export const h1 = createElement.bind(null, 'h1')
export const h2 = createElement.bind(null, 'h2')
export const h3 = createElement.bind(null, 'h3')
export const h4 = createElement.bind(null, 'h4')
export const h5 = createElement.bind(null, 'h5')
export const h6 = createElement.bind(null, 'h6')
export const i = createElement.bind(null, 'i')
export const ins = createElement.bind(null, 'ins')
export const mark = createElement.bind(null, 'mark')
export const p = createElement.bind(null, 'p')
export const pre = createElement.bind(null, 'pre')
export const q = createElement.bind(null, 'q')
export const rp = createElement.bind(null, 'rp')
export const rt = createElement.bind(null, 'rt')
export const ruby = createElement.bind(null, 'ruby')
export const s = createElement.bind(null, 's')
export const small = createElement.bind(null, 'small')
export const span = createElement.bind(null, 'span')
export const strong = createElement.bind(null, 'strong')
export const sup = createElement.bind(null, 'sup')
export const u = createElement.bind(null, 'u')
export const wbr = createElement.bind(null, 'wbr')

// Definition
export const abbr = createElement.bind(null, 'abbr')
export const address = createElement.bind(null, 'address')
export const cite = createElement.bind(null, 'cite')
export const code = createElement.bind(null, 'code')
export const data = createElement.bind(null, 'data')
export const dfn = createElement.bind(null, 'dfn')
export const kbd = createElement.bind(null, 'kbd')
export const samp = createElement.bind(null, 'samp')
export const time = createElement.bind(null, 'time')

const varTag = createElement.bind(null, 'var')
export { varTag as var }

// Document
export const body = createElement.bind(null, 'body')
export const head = createElement.bind(null, 'head')
export const html = createElement.bind(null, 'html')
export const title = createElement.bind(null, 'title')

// Form
export const datalist = createElement.bind(null, 'datalist')
export const fieldset = createElement.bind(null, 'fieldset')
export const form = createElement.bind(null, 'form')
export const input = createElement.bind(null, 'input')
export const keygen = createElement.bind(null, 'keygen')
export const label = createElement.bind(null, 'label')
export const legend = createElement.bind(null, 'legend')
export const optgroup = createElement.bind(null, 'optgroup')
export const option = createElement.bind(null, 'option')
export const output = createElement.bind(null, 'output')
export const select = createElement.bind(null, 'select')
export const textarea = createElement.bind(null, 'textarea')

// Layout
export const article = createElement.bind(null, 'article')
export const aside = createElement.bind(null, 'aside')
export const div = createElement.bind(null, 'div')
export const figcaption = createElement.bind(null, 'figcaption')
export const figure = createElement.bind(null, 'figure')
export const footer = createElement.bind(null, 'footer')
export const header = createElement.bind(null, 'header')
export const hgroup = createElement.bind(null, 'hgroup')
export const main = createElement.bind(null, 'main')
export const menu = createElement.bind(null, 'menu')
export const nav = createElement.bind(null, 'nav')
export const search = createElement.bind(null, 'search')
export const section = createElement.bind(null, 'section')
export const summary = createElement.bind(null, 'summary')

// List
export const dd = createElement.bind(null, 'dd')
export const dl = createElement.bind(null, 'dl')
export const dt = createElement.bind(null, 'dt')
export const li = createElement.bind(null, 'li')
export const ol = createElement.bind(null, 'ol')
export const ul = createElement.bind(null, 'ul')

// Metadata
export const base = createElement.bind(null, 'base')
export const meta = createElement.bind(null, 'meta')

// Hypermedia
export const a = createElement.bind(null, 'a')
export const audio = createElement.bind(null, 'audio')
export const embed = createElement.bind(null, 'embed')
export const iframe = createElement.bind(null, 'iframe')
export const img = createElement.bind(null, 'img')
export const link = createElement.bind(null, 'link')
export const object = createElement.bind(null, 'object')
export const param = createElement.bind(null, 'param')
export const picture = createElement.bind(null, 'picture')
export const script = createElement.bind(null, 'script')
export const source = createElement.bind(null, 'source')
export const track = createElement.bind(null, 'track')
export const video = createElement.bind(null, 'video')

// Table
export const caption = createElement.bind(null, 'caption')
export const col = createElement.bind(null, 'col')
export const colgroup = createElement.bind(null, 'colgroup')
export const table = createElement.bind(null, 'table')
export const tbody = createElement.bind(null, 'tbody')
export const td = createElement.bind(null, 'td')
export const tfoot = createElement.bind(null, 'tfoot')
export const th = createElement.bind(null, 'th')
export const thead = createElement.bind(null, 'thead')
export const tr = createElement.bind(null, 'tr')

// SVG
export const animate = createElement.bind(null, 'animate')
export const animateMotion = createElement.bind(null, 'animateMotion')
export const animateTransform = createElement.bind(null, 'animateTransform')
export const circle = createElement.bind(null, 'circle')
export const clipPath = createElement.bind(null, 'clipPath')
export const defs = createElement.bind(null, 'defs')
export const desc = createElement.bind(null, 'desc')
export const ellipse = createElement.bind(null, 'ellipse')
export const feBlend = createElement.bind(null, 'feBlend')
export const feColorMatrix = createElement.bind(null, 'feColorMatrix')
export const feComponentTransfer = createElement.bind(null, 'feComponentTransfer')
export const feComposite = createElement.bind(null, 'feComposite')
export const feConvolveMatrix = createElement.bind(null, 'feConvolveMatrix')
export const feDiffuseLighting = createElement.bind(null, 'feDiffuseLighting')
export const feDisplacementMap = createElement.bind(null, 'feDisplacementMap')
export const feDistantLight = createElement.bind(null, 'feDistantLight')
export const feDropShadow = createElement.bind(null, 'feDropShadow')
export const feFlood = createElement.bind(null, 'feFlood')
export const feFuncA = createElement.bind(null, 'feFuncA')
export const feFuncB = createElement.bind(null, 'feFuncB')
export const feFuncG = createElement.bind(null, 'feFuncG')
export const feFuncR = createElement.bind(null, 'feFuncR')
export const feGaussianBlur = createElement.bind(null, 'feGaussianBlur')
export const feImage = createElement.bind(null, 'feImage')
export const feMerge = createElement.bind(null, 'feMerge')
export const feMergeNode = createElement.bind(null, 'feMergeNode')
export const feMorphology = createElement.bind(null, 'feMorphology')
export const feOffset = createElement.bind(null, 'feOffset')
export const fePointLight = createElement.bind(null, 'fePointLight')
export const feSpecularLighting = createElement.bind(null, 'feSpecularLighting')
export const feSpotLight = createElement.bind(null, 'feSpotLight')
export const feTile = createElement.bind(null, 'feTile')
export const feTurbulence = createElement.bind(null, 'feTurbulence')
export const filter = createElement.bind(null, 'filter')
export const foreignObject = createElement.bind(null, 'foreignObject')
export const g = createElement.bind(null, 'g')
export const image = createElement.bind(null, 'image')
export const line = createElement.bind(null, 'line')
export const linearGradient = createElement.bind(null, 'linearGradient')
export const marker = createElement.bind(null, 'marker')
export const mask = createElement.bind(null, 'mask')
export const metadata = createElement.bind(null, 'metadata')
export const mpath = createElement.bind(null, 'mpath')
export const path = createElement.bind(null, 'path')
export const pattern = createElement.bind(null, 'pattern')
export const polygon = createElement.bind(null, 'polygon')
export const polyline = createElement.bind(null, 'polyline')
export const radialGradient = createElement.bind(null, 'radialGradient')
export const rect = createElement.bind(null, 'rect')
export const set = createElement.bind(null, 'set')
export const stop = createElement.bind(null, 'stop')
export const svg = createElement.bind(null, 'svg')

const switchTag = createElement.bind(null, 'switch')
export { switchTag as switch }

export const symbol = createElement.bind(null, 'symbol')
export const text = createElement.bind(null, 'text')
export const textPath = createElement.bind(null, 'textPath')
export const tspan = createElement.bind(null, 'tspan')
export const use = createElement.bind(null, 'use')
export const view = createElement.bind(null, 'view')
